// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTIAccountSaver.
NSObject<FlutterMessageCodec> *FLTIAccountSaverGetCodec(void);

@protocol FLTIAccountSaver
- (void)initDev:(NSNumber *)dev test:(NSNumber *)test release:(NSNumber *)release storeReleaseAccount:(NSNumber *)storeReleaseAccount completion:(void (^)(FlutterError *_Nullable))completion;
- (void)selectAccountHostType:(NSNumber *)hostType countryCode:(NSString *)countryCode completion:(void (^)(NSDictionary<NSString *, id> *_Nullable, FlutterError *_Nullable))completion;
- (void)saveAccountCurrentHostType:(NSNumber *)currentHostType countryCode:(NSString *)countryCode account:(NSString *)account pw:(NSString *)pw completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void FLTIAccountSaverSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTIAccountSaver> *_Nullable api);

NS_ASSUME_NONNULL_END
